### ISSUE TITLE
is the training data available?

### ISSUE THREAD

**Issue by tanganke** [sshh12/multi_token#17]
thank you for the great work. Is the fine-tuning data available?

![image](https://github.com/sshh12/multi_token/assets/33046358/78ef4c97-b673-4054-89fb-1d30369caebb)

**Comment by sshh12** [comment]
Hey! All of the dataset scripts are included and were run as-is.

e.g. https://github.com/sshh12/multi_token/blob/main/scripts/xclip_build_finetune_dataset.py

**Comment by tanganke** [comment]
Thank you very much!
