### ISSUE TITLE
Finetuning already trained model

### ISSUE THREAD

**Issue by Aniketto16** [sshh12/multi_token#5]
can I finetune this model ? 
https://huggingface.co/sshh12/Mistral-7B-LoRA-Multi-VisionCLIPPool-LLAVA 

If so how to do it, I am in a hurry so please reply as soon as possible! 
Thank you!

**Comment by sshh12** [comment]
Sure, you can just follow the instructions for https://github.com/sshh12/multi_token?tab=readme-ov-file#finetuning but use the the pre-existing projector from https://huggingface.co/sshh12/Mistral-7B-LoRA-Multi-VisionCLIPPool-LLAVA/blob/main/non_lora_trainables.bin

**Comment by Aniketto16** [comment]
Thank you so much, I understand!
