### ISSUE TITLE
theres nothing in my output

### ISSUE THREAD

**Issue by guilh00009** [sshh12/multi_token#7]
{'output': ''}

**Comment by sshh12** [comment]
What's your input? and the model you are running?

**Comment by guilh00009** [comment]
i tried an model of the mistral finetuned on a dataset, but its the same weights, i think

**Comment by guilh00009** [comment]
its my model:  Guilherme34/Samantha-v2

**Comment by guilh00009** [comment]
and that is my inference code: import requests

response = requests.post(
    "https://d032-34-87-126-184.ngrok-free.app/generate",
    json={
        "messages": [{"role": "user", "content": "What are things I should be cautious about when I visit this place? <image>"}],
        "images": ["https://github.com/sshh12/multi_token/raw/main/.demo/llava-view.jpg"],
    },
)

result = response.json()
print(result)

**Comment by sshh12** [comment]
Ah did you train it using the scripts in this repo? It looks like you potentially used something different https://huggingface.co/Guilherme34/Samantha-v2/tree/main

If this is just a text model, you'd need to finetune it first on image data to be able to use it multimodal.

**Comment by guilh00009** [comment]
oh okay, sorry for that lol, thank you

**Comment by sshh12** [comment]
Haha np
