### ISSUE TITLE
can you share an dataset to me use to train my vision model based on this?

### ISSUE THREAD

**Issue by guilh00009** [sshh12/multi_token#9]

**Comment by sshh12** [comment]
I used LLAVA's data -- these are all the scripts required:

* [llava_download_finetune.sh](https://github.com/sshh12/multi_token/blob/main/scripts/llava_download_finetune.sh)
* [llava_download_pretrain.sh](https://github.com/sshh12/multi_token/blob/main/scripts/llava_download_pretrain.sh)

* [llava_build_finetune_dataset.py](https://github.com/sshh12/multi_token/blob/main/scripts/llava_build_finetune_dataset.py)
* [llava_build_pretrain_dataset.py](https://github.com/sshh12/multi_token/blob/main/scripts/llava_build_pretrain_dataset.py)

**Comment by guilh00009** [comment]
can you share your training code with me? i've been trying for sooooo much time

**Comment by sshh12** [comment]
You can get `/non_lora.bin` from https://huggingface.co/sshh12/Mistral-7B-LoRA-VisionCLIPPool-LLAVA and set dataset_path to the output of the finetune dataset above.

```
WANDB_PROJECT=lmm-train WANDB_NAME=lmm_vision_clip_pool_finetune deepspeed scripts/train_model.py \
    --model_name_or_path mistralai/Mistral-7B-Instruct-v0.1 \
    --model_cls MistralLMMForCausalLM \
    --modality_builder vision_clip_pool \
    --dataset_path sshh12/llava-finetune \
    --output_dir /data/output/lmm_vision_clip_pool_finetune \
    --pretrained_projectors_path /root/non_lora.bin \
    --lora_enable True \
    --bf16 True \
    --tf32 True \
    --num_train_epochs 1 \
    --gradient_checkpointing True \
    --per_device_train_batch_size 1 \
    --per_device_eval_batch_size 1 \
    --gradient_accumulation_steps 16 \
    --model_max_length 2048 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 1000 \
    --save_total_limit 1 \
    --learning_rate 1e-5 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --dataloader_num_workers 2 \
    --logging_steps 1 \
    --report_to wandb \
    --deepspeed ./configs/zero2.json
```
